version: '{build}'
skip_tags: true
image: Visual Studio 2017
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Autofac.Analysis.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: TT3933EK0MerFigO2DoCnmV5HwiY0NmKDeh1iU1RNt/sjheUAjIJn4jPWLHPvKBR
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
